# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-07-08 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='comment',
            field=models.CharField(default='', max_length=50, verbose_name='\u6559\u5e08\u63cf\u8ff0'),
        ),
    ]
